/* eslint-disable */
/* prettier-ignore */
// @ts-nocheck
// Generated by vite-plugin-uni-pages

interface NavigateToOptions {
  url: "/pages/login/index" |
       "/pages/auth/bind-student" |
       "/pages/auth/forgot-account" |
       "/pages/auth/forgot-password" |
       "/pages/auth/reset-password" |
       "/pages/course/detail" |
       "/pages/course/index" |
       "/pages/home/index" |
       "/pages/mine/index" |
       "/pages/paper/index" |
       "/pages/register/index" |
       "/pages/resource/family-edu" |
       "/pages/resource/index" |
       "/pages/resource/paper" |
       "/pages/resource/student-talk" |
       "/pages/resource/sync-course" |
       "/pages/score/index" |
       "/pages/service/index" |
       "/pages/vip/index" |
       "/pages/vip/recharge" |
       "/pages/mine/settings/index";
}
interface RedirectToOptions extends NavigateToOptions {}

interface SwitchTabOptions {
  url: "/pages/home/index" | "/pages/resource/index" | "/pages/mine/index"
}

type ReLaunchOptions = NavigateToOptions | SwitchTabOptions;

declare interface Uni {
  navigateTo(options: UniNamespace.NavigateToOptions & NavigateToOptions): void;
  redirectTo(options: UniNamespace.RedirectToOptions & RedirectToOptions): void;
  switchTab(options: UniNamespace.SwitchTabOptions & SwitchTabOptions): void;
  reLaunch(options: UniNamespace.ReLaunchOptions & ReLaunchOptions): void;
}
