/* eslint-disable */
/* prettier-ignore */
// @ts-nocheck
// Generated by vite-plugin-uni-pages

interface NavigateToOptions {
  url: "/pages/login/index" |
       "/pages/auth/bind-student" |
       "/pages/auth/forgot-account" |
       "/pages/auth/forgot-password" |
       "/pages/auth/reset-password" |
       "/pages/home/index" |
       "/pages/mine/index" |
       "/pages/register/index" |
       "/pages/resource/index" |
       "/subpkg_resource/pages/family-edu" |
       "/subpkg_resource/pages/paper" |
       "/subpkg_resource/pages/paper-list" |
       "/subpkg_resource/pages/student-talk" |
       "/subpkg_resource/pages/sync-course" |
       "/subpkg_course/pages/course/index" |
       "/subpkg_course/pages/course/detail" |
       "/subpkg_course/pages/course/pay" |
       "/subpkg_course/pages/vip/index" |
       "/subpkg_course/pages/vip/recharge" |
       "/subpkg_course/pages/vip/school-status" |
       "/subpkg_analysis/pages/score/index" |
       "/subpkg_analysis/pages/score/composition" |
       "/subpkg_analysis/pages/score/distribution" |
       "/subpkg_analysis/pages/score/trend" |
       "/subpkg_analysis/pages/paper/index" |
       "/subpkg_mine/pages/mine/course-list" |
       "/subpkg_mine/pages/mine/about" |
       "/subpkg_mine/pages/mine/edit-profile" |
       "/subpkg_mine/pages/mine/order-list" |
       "/subpkg_mine/pages/mine/notifications" |
       "/subpkg_mine/pages/mine/notification-detail" |
       "/subpkg_mine/pages/mine/settings/index" |
       "/subpkg_mine/pages/service/index";
}
interface RedirectToOptions extends NavigateToOptions {}

interface SwitchTabOptions {
  url: "/pages/home/index" | "/pages/resource/index" | "/pages/mine/index"
}

type ReLaunchOptions = NavigateToOptions | SwitchTabOptions;

declare interface Uni {
  navigateTo(options: UniNamespace.NavigateToOptions & NavigateToOptions): void;
  redirectTo(options: UniNamespace.RedirectToOptions & RedirectToOptions): void;
  switchTab(options: UniNamespace.SwitchTabOptions & SwitchTabOptions): void;
  reLaunch(options: UniNamespace.ReLaunchOptions & ReLaunchOptions): void;
}
