SET FOREIGN_KEY_CHECKS = 0;

DROP TABLE IF EXISTS `sys_user_modules`;
DROP TABLE IF EXISTS `sys_role_menu`;

CREATE TABLE `sys_role_menu` (
    `id` BIGINT AUTO_INCREMENT PRIMARY KEY,
    `role_id` INT NOT NULL COMMENT '关联 sys_roles.id',
    `permission_code` VARCHAR(100) NOT NULL COMMENT '权限标识，例如 system:user:list',
    `create_time` DATETIME DEFAULT CURRENT_TIMESTAMP,
    UNIQUE KEY `uk_role_permission` (`role_id`, `permission_code`),
    INDEX `idx_role_id` (`role_id`),
    CONSTRAINT `fk_role_menu_role_id` FOREIGN KEY (`role_id`) REFERENCES `sys_roles` (`id`) ON DELETE CASCADE
) ENGINE=InnoDB COMMENT='角色与权限关联表';

INSERT INTO `sys_role_menu` (`role_id`, `permission_code`) VALUES
(1, 'dashboard:analysis:view'),
(1, 'system:school:list'),
(1, 'system:school:add'),
(1, 'system:school:edit'),
(1, 'system:school:delete'),
(1, 'system:school:import'),
(1, 'system:class:list'),
(1, 'system:class:add'),
(1, 'system:class:batch-add'),
(1, 'system:class:edit'),
(1, 'system:class:delete'),
(1, 'system:class:import'),
(1, 'system:class:detail'),
(1, 'system:student:list'),
(1, 'system:student:add'),
(1, 'system:student:edit'),
(1, 'system:student:delete'),
(1, 'system:student:import'),
(1, 'system:student:bound-parents'),
(1, 'exam:project:list'),
(1, 'exam:project:options'),
(1, 'exam:project:add'),
(1, 'exam:project:edit'),
(1, 'exam:project:delete'),
(1, 'exam:project:detail'),
(1, 'exam:project:students'),
(1, 'exam:project:score-summary'),
(1, 'exam:project:score-list'),
(1, 'exam:project:score-template'),
(1, 'exam:project:score-import'),
(1, 'exam:project:score-save'),
(1, 'exam:project:paper-import'),
(1, 'exam:project:paper-upload'),
(1, 'exam:class:list'),
(1, 'exam:class:add'),
(1, 'exam:class:edit'),
(1, 'exam:class:delete'),
(1, 'order:vip:list'),
(1, 'order:course:list'),
(1, 'order:print:list'),
(1, 'order:print:detail'),
(1, 'order:print:status'),
(1, 'course:manage:list'),
(1, 'course:manage:add'),
(1, 'course:manage:edit'),
(1, 'course:manage:delete'),
(1, 'course:manage:status'),
(1, 'paper:manage:list'),
(1, 'paper:manage:save'),
(1, 'paper:manage:delete'),
(1, 'paper:manage:upload'),
(1, 'paper:subject:list'),
(1, 'paper:subject:save'),
(1, 'paper:subject:delete'),
(1, 'payment:vip:list'),
(1, 'payment:vip:edit'),
(1, 'payment:print:list'),
(1, 'payment:print:edit'),
(1, 'support:faq:list'),
(1, 'support:faq:add'),
(1, 'support:faq:edit'),
(1, 'support:faq:delete'),
(1, 'support:faq-category:list'),
(1, 'support:faq-category:add'),
(1, 'support:faq-category:edit'),
(1, 'support:faq-category:delete'),
(1, 'support:wechat:list'),
(1, 'support:wechat:upload'),
(1, 'support:wechat:add'),
(1, 'support:wechat:edit'),
(1, 'support:wechat:delete'),
(1, 'system:user:list'),
(1, 'system:user:add'),
(1, 'system:user:edit'),
(1, 'system:user:delete'),
(1, 'system:user:import'),
(1, 'system:user:template'),
(1, 'system:role:list'),
(1, 'system:permission:list'),
(1, 'system:permission:edit'),
(1, 'system:permission:options'),
(1, 'system:log:list'),
(1, 'system:log:delete');

INSERT INTO `sys_role_menu` (`role_id`, `permission_code`)
SELECT 2, `permission_code`
FROM `sys_role_menu`
WHERE `role_id` = 1;

SET FOREIGN_KEY_CHECKS = 1;
